# This is a basic workflow to help you get started with Actions

name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r Ari_Roffe_BE_Task1_Submission.zip . -x ".git/*" ".github/*"
    - name: Release to Github
      run: echo "Release"
